# Generated by Django 5.2.8 on 2025-11-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0002_remove_user_role_user_is_admin_user_is_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_category',
        ),
    ]
