# Generated by Django 5.2.8 on 2025-11-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_orders_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
    ]
