# Generated by Django 5.2.8 on 2025-11-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_orders_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
    ]
