# Generated by Django 5.2.8 on 2025-11-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_remove_address_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
