# Generated by Django 5.2.8 on 2025-11-21 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='UserApp.address'),
            preserve_default=False,
        ),
    ]
