# Generated by Django 5.2.8 on 2025-11-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_contactmessage'),
        ('UserApp', '0007_orders_address'),
    ]

    operations = [
    ]
